blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/Sync-in/server/discussions
    about: Ask questions, start discussions, or share ideas about Sync-in.
  - name: ðŸŽ§ Discord Community
    url: https://discord.com/invite/qhJyzwaymT
    about: Join the Sync-in Discord community to get help, share your feedback, and stay updated on the project.