services:
  onlyoffice:
    image: onlyoffice/documentserver:9.0
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_SECRET=onlyOfficeSecret
      - JWT_IN_BODY=true
      - USE_UNAUTHORIZED_STORAGE=true
    logging:
      driver: json-file
      options:
        max-size: "25m"
        max-file: "5"
    networks:
      - sync_in_network